# Generated by Django 5.1.7 on 2025-04-07 22:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='fas fa-link', max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie de lien',
                'verbose_name_plural': 'Catégories de liens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='links/favicons/', verbose_name='Favicon')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de clics')),
                ('last_clicked', models.DateTimeField(blank=True, null=True, verbose_name='Dernier clic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.importantlinkcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Lien important',
                'verbose_name_plural': 'Liens importants',
                'ordering': ['-is_featured', 'title'],
                'indexes': [models.Index(fields=['title'], name='myapp_impor_title_5bfce8_idx'), models.Index(fields=['category'], name='myapp_impor_categor_0534a5_idx'), models.Index(fields=['is_featured'], name='myapp_impor_is_feat_9d2840_idx')],
            },
        ),
    ]
