# Generated by Django 5.1.7 on 2025-04-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_importantlinkcategory_importantlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantlink',
            name='favicon',
        ),
    ]
